name = "pronto-clean"
main = ".next/server/app/page.js"
compatibility_date = "2023-05-08"

[build]
command = "npm run build"

[site]
bucket = "./out"

[env.production]
name = "pronto-clean"
route = "prontoclean.com/*" 